[project]
site_name = "toto"
site_url = "https://toto-site-3pm.pages.dev"
extra_css = [
    "stylesheets/custom.css"
]

[project.theme]
name = "material"
logo = "images/toto-site-logo-white-med.png"
# CRITICAL: These features force Zensical to generate the sidebar layout blocks
features = [
    "navigation.tabs",
    "navigation.sections",
    "navigation.tracking",
    "content.code.copy"
]
